/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Student */

#ifndef _Included_Student
#define _Included_Student
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Student
 * Method:    callNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Student_callNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
